name: climagrow
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  intl: ^0.19.0
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.0.12
  flutter_gradient_colors: ^2.1.1
  geolocator: ^11.0.0
  http: any
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.29.0
  firebase_database: ^10.5.1
  cloud_firestore: ^4.16.1
  firebase_auth: ^4.19.1
  google_sign_in: ^6.2.1
  firebase_storage: ^11.7.1
  image_picker: ^1.0.8
  fluttertoast: ^8.2.4
  shared_preferences: ^2.2.3
  connectivity: ^3.0.6
  lottie: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/splash_animation/
